import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    pool: 'threads',
    environment: 'node',
    globals: true,
    include: ['tests/**/*.spec.ts'],
    exclude: ['tests/unit/github/**/*.spec.ts'],
    coverage: {
      provider: 'istanbul',
      reporter: ['text', 'html', 'lcov'],
      reportsDirectory: 'coverage',
      include: ['src/**/*.ts'],
      thresholds: {
        lines: 90,
        functions: 90,
        branches: 90,
        statements: 90,
      },
      exclude: [
        '../.github/**',
        'coverage/**',
        'eslint.config.js',
        'lib/**',
        'src/**/*.interface.ts',
        'src/**/index.ts',
        'src/**/bootstrap/**',
        'src/**/dtos/**',
        'src/**/models/**',
        'src/**/settings/**',
        'src/api/generated/**',
        'src/api/configuration/open-api.document.ts',
        'src/api/program.ts',
        'src/api/middlewares/**',
        'src/api/runtime/**',
        'src/core/health-check/**',
        'src/infrastructure/analytics/client/**',
        'src/infrastructure/**/healthchecks/**',
        'src/infrastructure/email/gmail/**',
        'src/infrastructure/email/node-pop3/client/**',
        'src/infrastructure/email/node-pop3/parser/**',
        'src/infrastructure/firestore/firestore-mappers.ts',
        'src/infrastructure/job-run-statistics/repositories/**',
        'src/infrastructure/logging/**',
        'src/jobs/email-transfer/email-transfer.function.ts',
        'tests/**',
        'vitest.config.ts',
      ],
    },
  },
});
