<Project>
  <PropertyGroup>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <CSharpier_Check>true</CSharpier_Check>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CSharpier.MSBuild" Version="1.2.6" PrivateAssets="all" />
  </ItemGroup>
</Project>
